#include "bitbase.h"

/* Bitboard tables to cache the generation of piece attacks. For all sliding piece moves, this uses
 * about 1MB of storage, which can fit into the larger caches on newer CPUs.
 */

#ifdef USE_PEXT
/* When using the BMI2 instruction set, we only need to store the move mask and can generate an
 * index into attacks using the 'pext' instruction.
 * */
typedef struct { bitboard mask, *attacks; } Magic;
#else
/* When using normal 'plain' magics, we also need to store the magic number, which is as perfect
 * hash using a multiply (*) and shift (>>) to generate an index into attacks.
 */
typedef struct { bitboard mask, magic, *attacks; } Magic;
#endif

static bitboard knight_attacks[64];
static bitboard   king_attacks[64];

static bitboard line_between[64][64];
static bitboard line_connecting[64][64];
static bitboard sliding_attacks[107648];

static Magic bishop_magics[64];
static Magic rook_magics[64];


/* Extract the attack bitboards from the tables:
 *	- knight/king moves and line between/connecting are thin wrapper functions
 *	- bishop/rook moves require calculating the index from the occupancy mask
 *	- queen moves are a union of bishop and rook moves
 */

bitboard knight_moves(square sq) { return knight_attacks[sq]; }
bitboard   king_moves(square sq) { return   king_attacks[sq]; }

bitboard get_line_between(square a, square b) { return line_between[a][b]; }
bitboard get_line_connecting(square a, square b) { return line_connecting[a][b]; }


#ifdef USE_PEXT
bitboard bishop_moves(square sq, bitboard occ) {
	bitboard index = pext(occ, bishop_magics[sq].mask);
	return bishop_magics[sq].attacks[index];
}

bitboard rook_moves(square sq, bitboard occ) {
	bitboard index = pext(occ, rook_magics[sq].mask);
	return rook_magics[sq].attacks[index];
}

#else
bitboard bishop_moves(square sq, bitboard occ) {
	bitboard index = 1 / 0; // unimplemented!
	return bishop_magics[sq].attacks[index];
}

bitboard rook_moves(square sq, bitboard occ) {
	bitboard index = 1 / 0; // unimplemented!
	return rook_magics[sq].attacks[index];
}

#endif


bitboard queen_moves(square sq, bitboard occ) {
	return bishop_moves(sq, occ) | rook_moves(sq, occ);
}


/* Generation of bitbase tables:
 *	- knight and king attack sets can be generated by shifting a pre-generated mask
 *	  and masking out the bits that wrap around the edges.
 *
 *	- sliding piece attacks are generated using hyperbola-quintessence
 *	  (https://www.chessprogramming.org/Hyperbola_Quintessence)
 *
 *	- we generate the indices iteratively for each square using the carry-rippler technique:
 *	  (https://www.chessprogramming.org/Traversing_Subsets_of_a_Set)
 */


/* Generate diagonal for bishop moves, the diagonals are from bottom-left to top-right, with the
 * main diagonal (index 0) being A1 to H8. The index (n) specifies the digonal, with positive
 * shifting the digonal toward A8, and negative toward H1.
 */
static inline
bitboard generate_diagonal(int n) {
	constexpr bitboard main_diag = 0x8040201008040201;
	return (n >= 0) ? main_diag << (8 * n) : main_diag >> (8 *- n);
}

/* The wrap-mask prevents pieces from moving around the edge of the board
 *    - if the square is on the  kingside, then the A and B files are cleared
 *    - if the square is on the queenside, then the G and H files are cleared
 */
static inline
bitboard wrap_mask(square sq) {
	constexpr bitboard wrap = 0x3F3F3F3F3F3F3F3F;
	return wrap << ((sq & 4) >> 1);
}


/* Generate knight moves using pre-calculated mask and offset, using the wrap mask to prevent
 * the moves from going around the edges of the board.
 */
static inline
bitboard generate_knight_attacks(square sq) {
	constexpr bitboard attacks = 0x508800885;
	constexpr square offset = 17;

	return ((sq >= offset) ? attacks << (sq - offset)
			       : attacks >> (offset - sq)) & wrap_mask(sq);
}

/* Generate king moves using the same technique as for knight moves above.
 */
static inline
bitboard generate_king_attacks(square sq) {
	constexpr bitboard attacks = 0x70507;
	constexpr square offset = 9;

	return ((sq >= offset) ? attacks << (sq - offset)
			       : attacks >> (offset - sq)) & wrap_mask(sq);
}


/* Generate sliding piece attacks using hyperbola quintessence.
 *  (https://www.chessprogramming.org/Hyperbola_Quintessence)
 */
static inline
bitboard generate_sliding_attacks(square sq, bitboard mask, bitboard occ)
{
	occ &= mask; // only use the occupancy of squares we need

	bitboard  bit = 1ull << sq;
	bitboard rbit = byteswap(bit);
	bitboard rocc = byteswap(occ);

	return ((occ - 2*bit) ^ byteswap(rocc - 2*rbit)) & mask;
}

/* Generate sliding rook attacks along a rank. This is a specialised method as we cannot byteswap
 * within a rank, so we need to map the rank to the main diagonal to generate the moves first, and
 * the map the diagonal back to the rank itself.
 */
static inline
bitboard generate_rank_attacks(square sq, bitboard occ)
{
	square file = sq & 7, rank = sq & 56;
	square mapped_sq = (file << 3) + file;

	/* Maps bits onto main diagonal */
	bitboard fill = ((occ >> rank) & RANK1) * AFILE; // fill bits in each file
	bitboard mask = generate_sliding_attacks(mapped_sq, generate_diagonal(0), fill);

	/* Map bits back to rank */
	return ((mask * AFILE) >> 56) << rank;
}


static inline
bitboard generate_line_between(square a, square b)
{
	bitboard bit_a = 1ull << a;
	bitboard bit_b = 1ull << b;

	bitboard diag = bishop_moves(a, bit_b);
	bitboard orth = rook_moves(a, bit_b);

	bitboard line = 0;

	if (diag & bit_b) line = diag & bishop_moves(b, bit_a);
	if (orth & bit_b) line = orth & rook_moves(b, bit_a);

	return line &~ (bit_a | bit_b);
}


static inline
bitboard generate_line_connecting(square a, square b)
{
	bitboard bit_a = 1ull << a;
	bitboard bit_b = 1ull << b;

	bitboard diag = bishop_moves(a, 0);
	bitboard orth = rook_moves(a, 0);

	bitboard line = 0;

	if (diag & bit_b) line = diag & bishop_moves(b, bit_a);
	if (orth & bit_b) line = orth & rook_moves(b, bit_a);

	return line &~ bit_a;
}


/* Initialise bitboard tables for lookup
 */
void init_bitbase_tables()
{
	size_t index = 0;

	for (square sq = 0; sq < 64; sq += 1)
	{
		knight_attacks[sq] = generate_knight_attacks(sq);
		king_attacks[sq]   = generate_king_attacks(sq);

		bitboard bit = 1ull << sq;

		// bishop attacks
		{
			square file = sq & 7, rank = sq >> 3;

			bitboard diag = generate_diagonal(rank - file);
			bitboard anti = byteswap(generate_diagonal(7 - rank - file));

			/* Clear outer bits of mask. These not needed for magic bitboards as a
			 * sliding piece can always move to the edge of the board if it can move
			 * to the square just before. We also clear the bit of the square as this
			 * is always occupied by the moving piece itself so is irrelvent.
			 */
			bitboard outer = AFILE | HFILE | RANK1 | RANK8 | bit;
			bitboard mask = (diag | anti) &~ outer;

			bishop_magics[sq].mask = mask;
			bishop_magics[sq].attacks = sliding_attacks + index;

			/* Carry-rippler iterator to iterate over subset of mask.
			 *  (https://www.chessprogramming.org/Traversing_Subsets_of_a_Set)
			 */

			bitboard occ = 0;

			do {
				sliding_attacks[index++] = generate_sliding_attacks(sq, diag, occ)
				                         | generate_sliding_attacks(sq, anti, occ);
				occ = (occ - mask) & mask;
			}
			while (occ);
		}

		// rook attacks
		{
			bitboard file = AFILE << (sq &  7);
			bitboard rank = RANK1 << (sq & 56);

			/* Rook moves are generated using the same techniques as bishop moves
			 * above, except more care must be taken with the board edges.
			 */

			constexpr bitboard file_outer = RANK1 | RANK8;
			constexpr bitboard rank_outer = AFILE | HFILE;

			bitboard mask = ((file &~ file_outer) | (rank &~ rank_outer)) &~ bit;

			rook_magics[sq].mask = mask;
			rook_magics[sq].attacks = sliding_attacks + index;

			bitboard occ = 0;

			do {
				sliding_attacks[index++] = generate_sliding_attacks(sq, file, occ)
				                         | generate_rank_attacks(sq, occ);
				occ = (occ - mask) & mask;
			}
			while (occ);
		}
	}

	/* Line-between and line-connecting are generated separately after as they rely on bishop
	 * and rook moves to already be generated.
	 */
	for (square a = 0; a < 64; a += 1) {
		for (square b = 0; b < 64; b += 1) {
			line_between[a][b] = generate_line_between(a,b);
			line_connecting[a][b] = generate_line_connecting(a,b);
		}
	}
}

